# Site settings
title: College Choice

description:
  Write an awesome description for your new site here.

baseurl: "/college-choice/" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

sass:
  style: nested

exclude:
  - js/vendor/node_modules
  - js/vendor/package.json
