# Site settings
title: College Scorecard

description:
  Helping prospective college students find the right school.

# the subpath of your site, e.g. /blog
baseurl: /college-choice

# Build settings
markdown: kramdown

sass:
  style: nested

# common site scripts, relative to `{{ site.baseurl }}/js/`
scripts:
  - vendor/aight.min.js
  - compat/custom-event.js
  - vendor/d3.min.js
  - vendor/async.min.js
  - vendor/querystring.min.js
  - vendor/document-register-element.min.js
  - components/aria-accordion.js
  - components/picc-meter.js
  - components/picc-range.js
  - components/multi-select.js
  - picc.js

stylesheets:
  - styles.css

# whether to include the Google Analytics & DAP snippets
analytics: true

# API configuration
API:
  baseurl: https://api.data.gov/TEST/ed/

# specify paths to exclude from copying to _site
# Note: files and directories with the '_' prefix are excluded
# automatically
exclude:
  # Node and JS asset build files
  - package.json
  - node_modules
  - '**/Makefile'
  - '*.sh'
  # Ruby stuff
  - 'Gemfile*'
  - config.ru
  # functional testing files
  - test/**
